-- MySQL Script generated by MySQL Workbench
-- Mon Jun  1 13:22:03 2026
-- Model: SmartRecipeFinder    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema smart_recipe_finder
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smart_recipe_finder`;
CREATE SCHEMA IF NOT EXISTS `smart_recipe_finder`
DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `smart_recipe_finder`;

-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`diets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`diets`;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`diets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`users`;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`dietary_restrictions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`dietary_restrictions`;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`dietary_restrictions` (
  `user_id` INT NOT NULL,
  `diet_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `diet_id`),
  INDEX `fk_dietary_restrictions_diet_idx` (`diet_id` ASC) VISIBLE,
  CONSTRAINT `fk_dietary_restrictions_diets`
    FOREIGN KEY (`diet_id`)
    REFERENCES `smart_recipe_finder`.`diets` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dietary_restrictions_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `smart_recipe_finder`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`households`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`households`;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`households` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` CHAR(8) NOT NULL,
  `nickname` VARCHAR(50) NULL DEFAULT NULL,
  `address` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`household_memberships`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`household_memberships`;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`household_memberships` (
  `household_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `date_added` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`household_id`, `user_id`),
  INDEX `fk_household_memberships_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_household_memberships_household`
    FOREIGN KEY (`household_id`)
    REFERENCES `smart_recipe_finder`.`households` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_household_memberships_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `smart_recipe_finder`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`ingredients`;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`ingredients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`intolerances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`intolerances`;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`intolerances` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`user_intolerances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`user_intolerances`;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`user_intolerances` (
  `user_id` INT NOT NULL,
  `intolerance_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `intolerance_id`),
  INDEX `fk_intolerances_items_idx` (`intolerance_id` ASC) VISIBLE,
  CONSTRAINT `fk_intolerances_items`
    FOREIGN KEY (`intolerance_id`)
    REFERENCES `smart_recipe_finder`.`intolerances` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_intolerances_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `smart_recipe_finder`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`inventory`;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`inventory` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `household_id` INT NOT NULL,
  `ingredient_id` INT NOT NULL,
  `quantity` DECIMAL(6,2) NULL DEFAULT NULL,
  `unit` VARCHAR(50) NULL DEFAULT NULL,
  `date_stored` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expiration` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `un_inventory_item` (`household_id` ASC, `ingredient_id` ASC, `expiration` ASC) VISIBLE,
  INDEX `fk_inventory_items_idx` (`ingredient_id` ASC) VISIBLE,
  CONSTRAINT `fk_inventory_households`
    FOREIGN KEY (`household_id`)
    REFERENCES `smart_recipe_finder`.`households` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inventory_items`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `smart_recipe_finder`.`ingredients` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`recipes`;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`recipes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `prep_time_in_mins` INT NULL DEFAULT NULL,
  `instructions` MEDIUMTEXT NULL DEFAULT NULL,
  `image_link` VARCHAR(2048) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`saved_recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`saved_recipes`;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`saved_recipes` (
  `user_id` INT NOT NULL,
  `recipe_id` INT NOT NULL,
  `date_saved` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `recipe_id`),
  INDEX `fk_saved_recipes_recipe_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_saved_recipes_recipes`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `smart_recipe_finder`.`recipes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_saved_recipes_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `smart_recipe_finder`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
