-- MySQL Script generated by MySQL Workbench
-- Fri May 29 12:57:32 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema smart_recipe_finder
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smart_recipe_finder` ;

-- -----------------------------------------------------
-- Schema smart_recipe_finder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smart_recipe_finder` DEFAULT CHARACTER SET utf8 ;
USE `smart_recipe_finder` ;

-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`users` ;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`items` ;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`recipes` ;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`recipes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `prep_time_in_mins` INT NULL,
  `instructions` MEDIUMTEXT NULL,
  `image_link` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`diets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`diets` ;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`diets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `diet_name` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`households`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`households` ;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`households` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` CHAR(8) NOT NULL,
  `nickname` VARCHAR(50) NULL,
  `address` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`household_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`household_users` ;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`household_users` (
  `household_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `date_added` DATE NULL,
  PRIMARY KEY (`household_id`, `user_id`),
  INDEX `fk_household_users_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_household_users_household_idx` (`household_id` ASC) VISIBLE,
  CONSTRAINT `fk_household_users_household`
    FOREIGN KEY (`household_id`)
    REFERENCES `smart_recipe_finder`.`households` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_household_users_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `smart_recipe_finder`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`user_recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`user_recipes` ;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`user_recipes` (
  `user_id` INT NOT NULL,
  `recipe_id` INT NOT NULL,
  `date_saved` DATE NULL,
  PRIMARY KEY (`user_id`, `recipe_id`),
  INDEX `fk_user_recipes_recipe_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_recipes_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `smart_recipe_finder`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_recipes_recipes`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `smart_recipe_finder`.`recipes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`inventory` ;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`inventory` (
  `household_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `quantity` FLOAT(24) NULL,
  `unit` VARCHAR(50) NULL,
  `date_stored` DATE NULL,
  `expiration` DATE NULL,
  PRIMARY KEY (`household_id`, `item_id`),
  INDEX `fk_user_has_inventoryItem_inventoryItem1_idx` (`item_id` ASC) VISIBLE,
  INDEX `fk_userInventory_household1_idx` (`household_id` ASC) VISIBLE,
  CONSTRAINT `fk_inventory_items`
    FOREIGN KEY (`item_id`)
    REFERENCES `smart_recipe_finder`.`items` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inventory_households`
    FOREIGN KEY (`household_id`)
    REFERENCES `smart_recipe_finder`.`households` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`intolerances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`intolerances` ;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`intolerances` (
  `user_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `item_id`),
  INDEX `fk_intolerances_item_idx` (`item_id` ASC) VISIBLE,
  INDEX `fk_intolerances_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_intolerances_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `smart_recipe_finder`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_intolerances_items`
    FOREIGN KEY (`item_id`)
    REFERENCES `smart_recipe_finder`.`items` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart_recipe_finder`.`user_diets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smart_recipe_finder`.`user_diets` ;

CREATE TABLE IF NOT EXISTS `smart_recipe_finder`.`user_diets` (
  `user_id` INT NOT NULL,
  `diet_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `diet_id`),
  INDEX `fk_user_diets_diet_idx` (`diet_id` ASC) VISIBLE,
  INDEX `fk_user_diets_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_diets_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `smart_recipe_finder`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_diets_diets`
    FOREIGN KEY (`diet_id`)
    REFERENCES `smart_recipe_finder`.`diets` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
